"""initial revisionn

Revision ID: 043a0539ed47
Revises: 
Create Date: 2024-03-04 11:26:43.442675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '043a0539ed47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_column('link', 'private')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('private', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('link', 'user_id')
    # ### end Alembic commands ###
